const express = require('express')
const app = express()
app.use(require('cors')())
app.use(express.json())
app.set('secret','fknaefnafla')
app.use('/uploads',express.static(__dirname + '/uploads'))
app.use('/admin',express.static(__dirname + '/admin'))
app.use('/',express.static(__dirname + '/web'))
require('./plugins/db')(app)
require('./routers/admin')(app)
require('./routers/web')(app)

app.listen(3000,()=>{
    console.log('ok,3000')
})